/**
 * lib/changelog-data.ts — release notes for the /changelog page.
 *
 * AUTO-GENERATED by scripts/generate_changelog.py from git
 * history + CHANGELOG.md. Do not edit by hand — re-run the
 * script instead. The backend mirror is GET /api/changelog.
 */

export interface ChangelogEntry {
  version: string;
  date: string;
  highlights: string[];
  summary: string;
  categories: {
    feature: string[];
    fix: string[];
    improvement: string[];
    breaking: string[];
  };
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: 'v1.0.0',
    date: '2026-09-07',
    highlights: ['public launch — 45 cogs, 167 commands, 34 dashboard modules', 'ai chat with persistent memory + personality', 'full veloura web dashboard with live previews', 'gentle moderation: warnings, ai automod, thresholds', 'engagement core: leveling, daily rewards, qotd, starboard', 'privacy-first: /privacy export + delete everywhere'],
    summary: 'the launch release — everything aurelia is today. five build phases, two live-test repair rounds and a full web dashboard later, she\'s ready for your server ♡',
    categories: {
      feature: ['phase m — public landing, docs site, stats, changelog, setup wizard, marketing assets (`836dced`)', 'live bot status card, env-driven dashboard domains, helpful login errors (`3a96697`)', 'dashboard phase C — all remaining module pages, realtime, privacy (`54c5138`)', 'dashboard phase B — leveling, qotd, moderation, custom commands, ai automod, statistics (`568d5c8`)', 'dashboard MVP — flask api, oauth flow, welcome module (`4d6ee9d`)', 'phase 3 — social & identity systems (ship, capsules, achievements, colors, nick requests, privacy) (`5f05a65`)', 'phase 2 — engagement core (daily rewards, qotd, anniversaries, recurring reminders, timezone utils, first-message welcome) (`c8daab6`)', 'phase 1 — infra hardening, 4 quick-win commands, aesthetic polish (`a254bdf`)', 'phase 4 — 8 new features (AI memory, AI automod, recap, starboard, giveaways, custom commands, proactive, onboarding) (`77102db`)', 'phase 2 — warnings migration, security hardening, non-blocking DB, dead-code purge, Aurelia rebrand (`920a716`)'],
      fix: ['overview Asset 500, dedicated sidebar routes, live polls page (`5279e1f`)', 'live-test round — live Discord channel/role pickers, permission-check race, icons, ux polish (`7c2100b`)', 'close single-line CoT edge case in _strip_cot_preambles (`1012a81`)', 'live-test batch — CoT leak elimination, whois title, /botinfo gating, /vibe freshness, usage-log silence (`4db1dcb`)', 'phase 7 — utility intents bypassed by AI chat, custom level-up messages, /welcome config consolidation (`0ba6bd0`)', 'phase 6 — live-test bug fixes + welcome UX rework (`d392eda`)', 'repair all 8 phase-4 features after live testing (`d0e9d46`)', 'moderation intents firing + status visibility + Mimu-style welcome polish (`e8612c8`)', 'P0 audit fixes — unified warnings store, prefix routing, intent ordering, prompt repair (`710a722`)', 'Mimu-style welcome system + remove /chat duplicate (`8700e0d`)'],
      improvement: ['fix gitignore entry for tsconfig.tsbuildinfo (`96c4bad`)', 'update default dashboard domain to aurelia.vercel.app (`d6c3eb2`)', 'dashboard setup, architecture and deployment guides (`de91cbf`)', 'complete command reference (`61bee44`)', 'veloura-aesthetic lowercase status rotation (`da564af`)', 'full code audit (10 sections, ~50 findings, P0-P3 roadmap) (`c6cbfe4`)'],
      breaking: [],
    },
  },
];

export const LATEST_VERSION: string = CHANGELOG[0]?.version ?? 'v1.0.0';
