"""
utils/public_api.py — PHASE M public (no-auth) marketing endpoints.

Serves everything the PUBLIC side of the site needs (landing stats bar,
/stats page, /changelog page, RSS). Registered onto the existing Flask
app in main.py:

    from utils.public_api import init_public_api
    init_public_api(app)   # registers the blueprint + history sampler

Endpoints (all JSON/XML, no auth — aggregated + anonymized only):

  GET /api/public/stats   -> live + fun + usage stats, 60s server cache
                             (spec PART 4: real-time, feature usage, fun
                             stats, growth history, version info)
  GET /api/changelog      -> JSON array of versions (spec PART 5)
  GET /changelog.rss      -> RSS 2.0 feed of the same versions

Security / fairness:
  * No personal data ever leaves this module — only aggregate counts,
    command NAMES (no user ids, no guild ids) and version strings.
  * Per-IP rate limit: 60 requests/minute (sliding window, in-memory).
  * CORS allow-list mirrors the dashboard API (DASHBOARD_URL + localhost
    dev origins).
  * 60-second response cache so a surge of visitors costs the bot
    nothing (spec: "Cached 60s").

Growth / uptime history:
  * A tiny daemon thread samples {servers, members, latency, status,
    uptime} every 10 minutes into data/public_stats_history.json (30-day
    ring buffer). This builds the /stats growth chart and the uptime
    percentage over time — passively, with zero Supabase writes.
  * A sample is also recorded opportunistically when /api/public/stats
    is called (if the newest sample is older than 10 minutes), so the
    graph grows exactly when people are actually looking.

Changelog source of truth: CHANGELOG.md in the repo root (generated by
scripts/generate_changelog.py). The parser is deliberately forgiving —
if the file is missing or malformed the endpoints return empty arrays
instead of erroring.

Implementation notes / deviations (documented):
  * PostgREST (Supabase) does not support arbitrary aggregates, so sums
    (total XP, confession counts, streak counts) fetch a single column
    and sum in Python. With the 60s response cache this is at most one
    lightweight query per minute. Every query is individually guarded —
    a failing table just renders "—" on the stats page.
  * Top commands come from the command_usage table (last 7 days,
    command_name only). If Supabase is unavailable the in-memory
    per-process command_counts (bot.command_counts) is used as a
    fallback — both are aggregate-only.
"""
import json
import logging
import os
import threading
import time
from collections import deque
from datetime import datetime, timedelta, timezone

from flask import Blueprint, Response, jsonify, request

logger = logging.getLogger('cyn.public_api')

BOT_VERSION = "1.0.0"

_repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHANGELOG_PATH = os.path.join(_repo_root, "CHANGELOG.md")
HISTORY_DIR = os.path.join(_repo_root, "data")
HISTORY_PATH = os.path.join(HISTORY_DIR, "public_stats_history.json")

DASHBOARD_URL = (os.getenv("DASHBOARD_URL") or "").rstrip("/")
_ALLOWED_ORIGINS = {o for o in (DASHBOARD_URL,) if o}
_ALLOWED_ORIGINS.update({
    "http://localhost:3000", "http://127.0.0.1:3000",
})

SAMPLE_INTERVAL_SECONDS = 600          # 10 minutes
HISTORY_KEEP_DAYS = 30
CACHE_TTL_SECONDS = 60                 # spec: cached 60s
RATE_LIMIT = 60                        # req/min/IP for public endpoints

public_bp = Blueprint("public_api", __name__)

# ─── tiny per-IP rate limiter (public endpoints only) ──────────────
_rl_lock = threading.Lock()
_rl_map: dict = {}


def _rate_ok(ip: str) -> bool:
    now = time.time()
    with _rl_lock:
        window = _rl_map.setdefault(ip, deque())
        while window and now - window[0] > 60:
            window.popleft()
        if len(window) >= RATE_LIMIT:
            return False
        window.append(now)
        return True


# ─── response caches ───────────────────────────────────────────────
_stats_cache = {"at": 0.0, "data": None}
_changelog_cache = {"at": 0.0, "data": None}
_cache_lock = threading.Lock()


# ─── history ring buffer (data/public_stats_history.json) ──────────
def _load_history() -> list:
    try:
        with open(HISTORY_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else []
    except Exception:
        return []


def _save_history(history: list) -> None:
    try:
        os.makedirs(HISTORY_DIR, exist_ok=True)
        tmp = HISTORY_PATH + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(history, f)
        os.replace(tmp, HISTORY_PATH)
    except Exception as e:
        logger.debug(f"[public] could not save stats history: {e}")


def _record_sample() -> None:
    """Append one {time, servers, members, latency, status, uptime}
    sample if the newest sample is older than SAMPLE_INTERVAL_SECONDS."""
    history = _load_history()
    now = time.time()
    if history:
        try:
            last_t = history[-1].get("t", 0)
            if isinstance(last_t, (int, float)) and now - last_t < SAMPLE_INTERVAL_SECONDS:
                return
        except Exception:
            pass

    import keep_alive as kl  # same late import pattern as main.py /health
    b = kl.bot_ref
    ready = bool(b) and bool(getattr(b, "is_ready", lambda: False)())
    sample = {
        "t": int(now),
        "s": len(b.guilds) if ready else 0,
        "m": (sum(g.member_count for g in b.guilds) if ready else 0),
        "lat": (round(b.latency * 1000, 1) if ready else 0),
        "ok": ready,
        "up": int((datetime.utcnow() - kl.start_time).total_seconds())
        if getattr(kl, "start_time", None) else 0,
    }
    history.append(sample)
    cutoff = now - HISTORY_KEEP_DAYS * 86400
    history = [h for h in history if isinstance(h.get("t"), (int, float)) and h["t"] >= cutoff]
    _save_history(history)


def _history_sampler() -> None:
    """Daemon thread — one sample every 10 minutes, forever."""
    while True:
        try:
            _record_sample()
        except Exception as e:
            logger.debug(f"[public] history sampler error: {e}")
        time.sleep(SAMPLE_INTERVAL_SECONDS)


_sampler_started = False


def _start_history_sampler() -> None:
    global _sampler_started
    if _sampler_started:
        return
    _sampler_started = True
    threading.Thread(target=_history_sampler, daemon=True,
                     name="public-stats-sampler").start()
    logger.info("✅ public stats history sampler started (10 min interval)")


# ─── aggregate DB helpers (all anonymized) ─────────────────────────
def _sum_column(table: str, column: str, where: list | None = None) -> int | None:
    """Sum one numeric column. Returns None when Supabase is down so the
    UI can show '—' instead of a wrong 0."""
    try:
        from utils.db import get_supabase
        sb = get_supabase()
        if not sb:
            return None
        q = sb.table(table).select(column)
        for col, val in (where or []):
            q = q.eq(col, val)
        rows = q.execute().data or []
        total = 0
        for r in rows:
            v = r.get(column)
            if isinstance(v, (int, float)):
                total += v
        return total
    except Exception as e:
        logger.debug(f"[public] sum({table}.{column}) failed: {e}")
        return None


def _count_rows(table: str) -> int | None:
    try:
        from utils.db import get_supabase
        sb = get_supabase()
        if not sb:
            return None
        res = sb.table(table).select("count", count="exact").execute()
        cnt = getattr(res, "count", None)
        return int(cnt) if cnt is not None else None
    except Exception as e:
        logger.debug(f"[public] count({table}) failed: {e}")
        return None


def _top_commands(days: int = 7, limit: int = 20) -> list:
    """Command names + counts only (no user ids, no guild ids)."""
    try:
        from utils.db import get_supabase
        sb = get_supabase()
        if sb:
            since = (datetime.now(timezone.utc) - timedelta(days=days)) \
                .isoformat()
            rows = sb.table("command_usage").select("command_name") \
                .gte("timestamp", since).execute().data or []
            counts: dict = {}
            for r in rows:
                name = r.get("command_name") or "unknown"
                counts[name] = counts.get(name, 0) + 1
            top = sorted(counts.items(), key=lambda kv: -kv[1])[:limit]
            return [{"command": k, "count": v} for k, v in top]
    except Exception as e:
        logger.debug(f"[public] top_commands failed: {e}")
    # fallback: per-process in-memory counters
    try:
        import keep_alive as kl
        b = kl.bot_ref
        counts = getattr(b, "command_counts", {}) or {}
        top = sorted(counts.items(), key=lambda kv: -kv[1])[:limit]
        return [{"command": k, "count": v} for k, v in top]
    except Exception:
        return []


def _commands_today() -> int | None:
    try:
        from utils.db import get_supabase
        sb = get_supabase()
        if not sb:
            return None
        today = datetime.now(timezone.utc).replace(
            hour=0, minute=0, second=0, microsecond=0).isoformat()
        res = sb.table("command_usage").select("count", count="exact") \
            .gte("timestamp", today).execute()
        cnt = getattr(res, "count", None)
        return int(cnt) if cnt is not None else None
    except Exception as e:
        logger.debug(f"[public] commands_today failed: {e}")
        return None


# ─── history → chart series ────────────────────────────────────────
def _growth_series(history: list) -> list:
    """One point per day (last sample of that day) for the growth chart."""
    per_day: dict = {}
    for h in history:
        t = h.get("t")
        if not isinstance(t, (int, float)):
            continue
        day = datetime.fromtimestamp(t, tz=timezone.utc).strftime("%Y-%m-%d")
        per_day[day] = h  # later samples overwrite earlier ones
    days = sorted(per_day.items())
    return [{"date": d, "servers": int(h.get("s", 0)),
             "members": int(h.get("m", 0))} for d, h in days]


def _latency_series(history: list) -> list:
    out = []
    for h in history:
        t = h.get("t")
        lat = h.get("lat")
        if isinstance(t, (int, float)) and isinstance(lat, (int, float)):
            out.append({"t": int(t), "latency_ms": lat})
    return out[-432:]  # ~3 days of 10-min samples


def _uptime_percent(history: list) -> float | None:
    samples = [h for h in history if "ok" in h]
    if len(samples) < 5:
        return None
    ok = sum(1 for h in samples if h.get("ok"))
    return round(ok / len(samples) * 100, 2)


# ─── stats collection ──────────────────────────────────────────────
def _collect_stats() -> dict:
    import keep_alive as kl
    b = kl.bot_ref
    ready = bool(b) and bool(getattr(b, "is_ready", lambda: False)())
    servers = len(b.guilds) if ready else 0
    members = sum(g.member_count for g in b.guilds) if ready else 0
    latency = round(b.latency * 1000, 1) if ready else 0
    uptime_seconds = 0
    if getattr(kl, "start_time", None):
        uptime_seconds = int(
            (datetime.utcnow() - kl.start_time).total_seconds())
    response_times = getattr(kl, "recent_response_times", [])
    avg_response = (round(sum(response_times) / len(response_times), 1)
                    if response_times else 0.0)

    history = _load_history()

    return {
        "status": "ok" if ready else "starting",
        "version": BOT_VERSION,
        "servers": servers,
        "members": members,
        "latency_ms": latency,
        "uptime_seconds": uptime_seconds,
        "uptime_percent": _uptime_percent(history),
        "avg_response_ms": avg_response,
        "commands_used_today": _commands_today(),
        "top_commands": _top_commands(),
        "fun_stats": {
            "total_xp": _sum_column("user_levels", "xp"),
            "warnings_issued": _count_rows("warnings"),
            "confessions_posted": _sum_column("confess_settings", "count"),
            "memories_stored": _count_rows("user_memory"),
            "daily_streaks_active": _count_rows("daily_streaks"),
        },
        "growth": _growth_series(history),
        "latency_history": _latency_series(history),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


# ─── changelog parsing (forgiving) ─────────────────────────────────
_CATEGORY_MAP = {
    "features": "feature",
    "feature": "feature",
    "fixes": "fix",
    "fix": "fix",
    "improvements": "improvement",
    "improvement": "improvement",
    "breaking changes": "breaking",
    "breaking": "breaking",
}


def _parse_changelog() -> list:
    """CHANGELOG.md (## [vX.Y.Z] — date · ### category · - items)
    -> [{version, date, categories: {feature: [...]}}]. Never raises."""
    try:
        with open(CHANGELOG_PATH, "r", encoding="utf-8") as f:
            text = f.read()
    except Exception:
        return []

    versions: list = []
    current_version = None
    current_category = None
    highlights = []

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("<!--"):
            continue
        if line.startswith("## ["):
            # e.g. "## [v1.0.0] — 2026-09-07"
            inner = line[4:]
            pieces = inner.split("]", 1)
            version_str = pieces[0].strip()
            date_str = pieces[1].replace("—", "").replace("--", "").strip() \
                if len(pieces) > 1 else ""
            current_version = {
                "version": version_str,
                "date": date_str,
                "categories": {"feature": [], "fix": [],
                               "improvement": [], "breaking": []},
                "highlights": [],
            }
            versions.append(current_version)
            current_category = None
            highlights = []
            continue
        if current_version is None:
            continue
        if line.startswith("### "):
            cat_key = line[4:].strip().lower()
            current_category = _CATEGORY_MAP.get(cat_key)
            continue
        if line.startswith("> highlights:") or line.startswith("**highlights:**"):
            highlights = [p.strip() for p in
                          line.split(":", 1)[1].split("·") if p.strip()]
            current_version["highlights"] = highlights
            continue
        if line.startswith("- ") and current_category:
            item = line[2:].strip()
            if item:
                current_version["categories"][current_category].append(item)
            continue
        # free-form paragraphs between the version heading and the first
        # category heading become the entry's highlights when short
        if not current_category and current_version and len(line) < 120 \
                and not line.startswith(("#", "`", "|")):
            pass  # prose intro — kept out of the API (summary only)

    return versions


# ─── RSS 2.0 ───────────────────────────────────────────────────────
def _rss(versions: list) -> str:
    base = DASHBOARD_URL or "http://localhost:3000"
    items = []
    for v in versions:
        cats = v.get("categories", {})
        parts = []
        for label in ("feature", "fix", "improvement", "breaking"):
            for entry in cats.get(label, []):
                parts.append(f"[{label}] {entry}")
        body = "<br>".join(
            e.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;")
            for e in parts) or "release notes"
        title = f"aurelia {v.get('version', '')} — {v.get('date', '')}".strip(" —")
        items.append(f"""    <item>
      <title>{_xml_escape(title)}</title>
      <link>{base}/changelog</link>
      <guid isPermaLink="false">aurelia-{_xml_escape(v.get('version', ''))}</guid>
      <description>{_xml_escape(body)}</description>
    </item>""")
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>aurelia changelog</title>
    <link>{base}/changelog</link>
    <description>release notes for aurelia — the soft, elegant discord bot ✦</description>
    <language>en</language>
{''.join(items)}
  </channel>
</rss>
"""


def _xml_escape(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


# ─── routes ────────────────────────────────────────────────────────
@public_bp.route("/api/public/stats", methods=["GET"])
def public_stats():
    if not _rate_ok(request.headers.get("X-Forwarded-For",
                                        request.remote_addr or "")):
        return jsonify({"error": "slow down ✦"}), 429
    now = time.time()
    with _cache_lock:
        if _stats_cache["data"] is None or now - _stats_cache["at"] > CACHE_TTL_SECONDS:
            _stats_cache["data"] = _collect_stats()
            _stats_cache["at"] = now
    # record a sample opportunistically (never blocks the response)
    threading.Thread(target=_record_sample, daemon=True).start()
    return jsonify(_stats_cache["data"])


@public_bp.route("/api/changelog", methods=["GET"])
def changelog_json():
    if not _rate_ok(request.headers.get("X-Forwarded-For",
                                        request.remote_addr or "")):
        return jsonify({"error": "slow down ✦"}), 429
    now = time.time()
    with _cache_lock:
        if _changelog_cache["data"] is None \
                or now - _changelog_cache["at"] > CACHE_TTL_SECONDS:
            _changelog_cache["data"] = _parse_changelog()
            _changelog_cache["at"] = now
    return jsonify({"versions": _changelog_cache["data"]})


@public_bp.route("/changelog.rss", methods=["GET"])
def changelog_rss():
    return Response(_rss(_parse_changelog()), mimetype="application/rss+xml")


@public_bp.after_request
def _public_cors(resp):
    origin = request.headers.get("Origin", "")
    if origin and origin in _ALLOWED_ORIGINS:
        resp.headers["Access-Control-Allow-Origin"] = origin
        resp.headers["Vary"] = "Origin"
        resp.headers["Access-Control-Allow-Methods"] = "GET, OPTIONS"
        resp.headers["Access-Control-Allow-Headers"] = "Content-Type"
        resp.headers["Access-Control-Max-Age"] = "300"
        return resp
    # public read-only marketing endpoints: same-origin dashboard fetches
    # (via NEXT_PUBLIC_API_URL) plus the allow-list above. For any other
    # origin we still serve the response (no CORS headers = browser
    # blocks reading it) — curl/bots remain fine.
    return resp


# ─── registration hook (called from main.py) ───────────────────────
def init_public_api(app):
    app.register_blueprint(public_bp)
    _start_history_sampler()
    logger.info("✅ Public API registered: /api/public/stats, /api/changelog, "
                "/changelog.rss")
