"""
cogs/proactive.py — PHASE 4 Feature 7: proactive presence.

Aurelia occasionally initiates conversation in configured channels instead
of only replying when mentioned — "it's quiet in here... anyone awake? ✦".

Behavior:
  - a background loop wakes every 20 minutes
  - for each guild with proactive enabled, there's a 20% chance per wake
    (≈ once per 100 min on average) that she speaks, IF at least 3h have
    passed since her last proactive message in that guild
  - the message is generated by the fast model with a fresh-randomized
    prompt so lines never repeat mechanically

Commands (manage_guild):
  /proactive toggle <on|off>
  /proactive channel <#channel>   — add a channel to the rotation
  /proactive status
"""
import logging
import random
import asyncio
import time
import discord
from discord.ext import commands, tasks
from discord import app_commands
from utils.ai_handler import call_ai_fast
from utils.db import get_guild_setting_async, set_guild_setting_async
from utils.veloura_embeds import COLOR_LAVENDER, COLOR_PINK

logger = logging.getLogger('cyn.proactive')

_WAKE_INTERVAL_MINUTES = 20
_CHANCE_PER_WAKE = 0.20          # ≈ once per ~100 min on average
_MIN_GAP_SECONDS = 3 * 3600     # min time between proactive msgs per guild

_PROMPT_STYLES = [
    "a cozy late-night observation about the server or the quiet",
    "a soft curious question to whoever is still awake",
    "a tiny thought you had while watching the chat",
    "something gentle about the time of day or the season",
    "a playful one-liner inviting people to talk about their day",
]


class Proactive(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        # {guild_id: epoch_of_last_proactive_message}
        self._last_spoke = {}
        if not self.proactive_loop.is_running():
            self.proactive_loop.start()

    def cog_unload(self):
        self.proactive_loop.cancel()

    # ─── config helpers ──────────────────────────────────────────

    async def _get_config(self, guild_id: int) -> dict:
        cfg = await get_guild_setting_async(guild_id, "proactive_settings")
        return {
            'enabled': bool(cfg.get('enabled')) if cfg else False,
            'channel_ids': (cfg or {}).get('channel_ids') or [],
        }

    async def _save_config(self, guild_id: int, cfg: dict):
        await set_guild_setting_async(guild_id, "proactive_settings", cfg)

    # ─── the loop ────────────────────────────────────────────────

    @tasks.loop(minutes=_WAKE_INTERVAL_MINUTES)
    async def proactive_loop(self):
        try:
            for guild in list(self.bot.guilds):
                try:
                    cfg = await self._get_config(guild.id)
                    if not cfg.get('enabled') or not cfg.get('channel_ids'):
                        continue
                    # chance gate
                    if random.random() > _CHANCE_PER_WAKE:
                        continue
                    # cooldown gate
                    last = self._last_spoke.get(guild.id, 0)
                    if time.time() - last < _MIN_GAP_SECONDS:
                        continue
                    await self._speak(guild, cfg)
                except Exception as e:
                    logger.error(
                        f"[proactive] guild {guild.id} error: "
                        f"{type(e).__name__}: {e}"
                    )
        except Exception as e:
            logger.error(f"[proactive] loop error: {type(e).__name__}: {e}")

    @proactive_loop.before_loop
    async def before_loop(self):
        await self.bot.wait_until_ready()
        await asyncio.sleep(120)  # settle 2 min after startup before speaking

    async def _speak(self, guild: discord.Guild, cfg: dict):
        channel_ids = [c for c in cfg.get('channel_ids', [])
                       if isinstance(c, (str, int))]
        if not channel_ids:
            return
        random.shuffle(channel_ids)
        for cid in channel_ids:
            channel = guild.get_channel(int(cid))
            if not channel or not isinstance(channel, discord.TextChannel):
                continue
            perms = channel.permissions_for(guild.me)
            if not (perms.send_messages and perms.view_channel):
                continue

            style = random.choice(_PROMPT_STYLES)
            prompt = (
                "you are aurelia — soft, elegant, lowercase, slightly playful "
                "community bot of a discord server. you are sending ONE "
                "spontaneous message to the chat out of your own initiative. "
                f"write {style}. max 12 words. one ♡ or ✩ emoji max, or none. "
                "no questions like 'how can i help'. no greeting like 'hi guys'. "
                "just the message text itself, nothing else."
            )
            try:
                line = await call_ai_fast(
                    [{"role": "system", "content": prompt},
                     {"role": "user", "content": "write your message"}],
                    max_tokens=300,
                )
            except Exception as e:
                logger.error(f"[proactive] AI call failed: {e}")
                return
            if not line or "something broke" in line or "at capacity" in line:
                return
            line = line.strip().strip('"')[:200]
            try:
                await channel.send(line)
                self._last_spoke[guild.id] = time.time()
                logger.info(
                    f"[proactive] spoke in guild {guild.id} #{channel.name}"
                )
                return  # one message per wake per guild
            except discord.HTTPException as e:
                logger.warning(f"[proactive] send failed in #{channel.name}: {e}")
                continue  # try the next configured channel

    # ─── commands ────────────────────────────────────────────────

    proactive = app_commands.Group(
        name="proactive",
        description="Let aurelia speak on her own",
    )

    @proactive.command(name="toggle", description="Enable or disable proactive presence")
    @app_commands.checks.has_permissions(manage_guild=True)
    @app_commands.choices(state=[
        app_commands.Choice(name="on", value="on"),
        app_commands.Choice(name="off", value="off"),
    ])
    async def proactive_toggle(self, interaction: discord.Interaction,
                               state: app_commands.Choice[str]):
        self.bot.increment_command('proactive_toggle')
        cfg = await self._get_config(interaction.guild.id)
        cfg['enabled'] = (state.value == "on")
        await self._save_config(interaction.guild.id, cfg)
        warn = ""
        if cfg['enabled'] and not cfg.get('channel_ids'):
            warn = "\n⚠️ no channels set — use /proactive channel first."
        embed = discord.Embed(
            title="꒰ა ♡ ໒꒱ proactive",
            description=f"proactive presence is now **{state.value}**.{warn}",
            color=COLOR_PINK if cfg['enabled'] else COLOR_LAVENDER,
        )
        await interaction.response.send_message(embed=embed, ephemeral=True)

    @proactive.command(name="channel", description="Add a channel to the proactive rotation")
    @app_commands.checks.has_permissions(manage_guild=True)
    @app_commands.describe(channel="Channel aurelia may speak in")
    async def proactive_channel(self, interaction: discord.Interaction,
                                 channel: discord.TextChannel):
        self.bot.increment_command('proactive_channel')
        cfg = await self._get_config(interaction.guild.id)
        ids = [str(c) for c in cfg.get('channel_ids', [])]
        if str(channel.id) in ids:
            # toggle OFF if already present
            ids.remove(str(channel.id))
            action = f"removed {channel.mention} from the rotation"
        else:
            if len(ids) >= 5:
                await interaction.response.send_message(
                    "rotation is full — 5 channels max.", ephemeral=True
                )
                return
            ids.append(str(channel.id))
            action = f"added {channel.mention} to the rotation"
        cfg['channel_ids'] = ids
        await self._save_config(interaction.guild.id, cfg)
        embed = discord.Embed(
            title="꒰ა ♡ ໒꒱ proactive",
            description=action,
            color=COLOR_PINK,
        )
        await interaction.response.send_message(embed=embed, ephemeral=True)

    @proactive.command(name="status", description="Show proactive presence settings")
    @app_commands.checks.has_permissions(manage_guild=True)
    async def proactive_status(self, interaction: discord.Interaction):
        self.bot.increment_command('proactive_status')
        cfg = await self._get_config(interaction.guild.id)
        mentions = []
        for cid in cfg.get('channel_ids', []):
            ch = interaction.guild.get_channel(int(cid))
            mentions.append(ch.mention if ch else f"`{cid}` (deleted)")
        embed = discord.Embed(
            title="꒰ა ♡ ໒꒱ proactive",
            description=(
                f"**enabled:** `{cfg['enabled']}`\n"
                f"**channels:** {', '.join(mentions) if mentions else 'none'}\n\n"
                f"speaks roughly once every 1-2 hours, at least 3h apart, "
                f"in one of the configured channels."
            ),
            color=COLOR_LAVENDER,
        )
        await interaction.response.send_message(embed=embed, ephemeral=True)


async def setup(bot):
    await bot.add_cog(Proactive(bot))
